### ISSUE TITLE
Annual Statistics Report

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#114]
Automated annual report to UNFCCC and national statistics office 
<img width="687" alt="image" src="https://github.com/undp/carbon-registry/assets/109564/ef919841-13ea-4660-a41f-f74f34a2bf12">
<img width="648" alt="image" src="https://github.com/undp/carbon-registry/assets/109564/b6e21da5-ba7c-4664-b204-7a958d6ca6f8">
to be done in CSV file

**Comment by mbelinsky** [comment]
Need the latest version from the technical committee

**Comment by mbelinsky** [comment]
Draft version of the agreed electronic format referred to in decision 2/CMA.3, annex, chapter IV.B (Annual information) via https://unfccc.int/documents/624366 from agreement https://unfccc.int/sites/default/files/resource/cma2022_10a02_adv.pdf 
File = [Draft_version_of_agreed_electronic_format.xlsx](https://github.com/undp/carbon-registry/files/12399095/Draft_version_of_agreed_electronic_format.xlsx)

**Comment by sapumalxep** [comment]
Field Clarifications based on Discussion:
1. Article 6 ID - Programme ID
2. Cooperative Approach - Programme Name
3. Authorization ID - Link to programme web page
4. First Transfer Definition - Authorized/Cancel etc state.
**5. First Transfer - Clarification pending**

**Comment by sapumalxep** [comment]
Issue moved to testing.

**Comment by sapumalxep** [comment]
Testing complete.

**Comment by sapumalxep** [comment]
Changes deployed.
