### ISSUE TITLE
National Share of Proceeds (SOP) Account

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#118]
SOP is an account that owns X% of every programme. Nationally defined. Rounding down to whole number.

**Comment by sapumalxep** [comment]
Field Clarifications based on Discussion:
1. Article 6 ID - Programme ID
2. Cooperative Approach - Programme Name
3. Authorization ID - Link to programme web page
4. First Transfer Definition - Authorized/Cancel etc state.
**5. First Transfer - Clarification pending**

**Comment by sapumalxep** [comment]
Issue moved to testing.

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
5b5e92b
