### ISSUE TITLE
Associated ministries can approve programmes under their responsibility

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#120]
New Level of auth.

**Comment by sapumalxep** [comment]
@mbelinsky Is it only for programme approval? 

How will it affect the following for example?

- Create Program
- Credit Issuance
- Credit Transfer
- Document Approval

**Comment by mbelinsky** [comment]
User story: I am an admin from the Ministry of Energy. I can log in and filter to see only energy programmes. For these programmes I can perform all current government tasks. For programmes controlled by other ministries (eg. waste), I cannot. I can manage users under my ministry.

**Comment by sapumalxep** [comment]
Issue undergoing testing. Currently undergoing bug fixes.

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
#144
