### ISSUE TITLE
Sectoral Scope tied to sector

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#121]

**Comment by sapumalxep** [comment]
@mbelinsky Require the mapping of Sectors and Sectoral Scopes

**Comment by mbelinsky** [comment]
| Sector     | Mitigation Action                   | Sectoral Scope                                                    |
|---------------|-----------------------------|--------------------------------------------------------------|
| Energy        | Biomass energy              | Energy industries (renewable - / non-renewable sources)      |
| Energy        | Coal bed/mine methane       | Energy distribution                                          |
| Energy        | EE households               | Energy demand                                                |
| Energy        | EE industry                 | N/A                                                          |
| Energy        | EE own generation           | N/A                                                          |
| Energy        | EE service                  | N/A                                                          |
| Energy        | EE supply side              | N/A                                                          |
| Energy        | Energy distribution         | N/A                                                          |
| Energy        | Fossil fuel switch          | N/A                                                          |
| Energy        | Geothermal                  | N/A                                                          |
| Energy        | Hydro                       | N/A                                                          |
| Energy        | Solar                       | N/A                                                          |
| Energy        | Wind                        | N/A                                                          |
| Health        | N/A                         | N/A                                                          |
| Education     | N/A                         | N/A                                                          |
| Transport     | Transport                   | Transport                                                    |
| Manufacturing | Cement                      | Manufacturing industries                                      |
| Manufacturing | CCS                         | Chemical industries                                           |
| Manufacturing | HFCs, PFCs, SF6             | Metal production                                              |
| Hospitality   | N/A                         | N/A                                                          |
| Forestry      | Forestry                    | Afforestation and reforestation                               |
| Waste         | Landfills                   | Waste handling and disposal                                  |
| Waste         | Fugitive                    | Fugitive emissions from fuels (solid, oil and gas)           |
| Waste         | Methane avoidance           | N/A                                                          |
| Agriculture   | Agriculture                 | Agriculture                                                  |
| Other         | Marine                      | Mining/mineral production                                    |
| Other         | N2O                         | Construction                                                 |
| Other         | N/A                         | Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride |
| Other         | N/A                         | Solvent use                                                  |

**Comment by mbelinsky** [comment]
Display all sectoral scopes when sector is n/a
