### ISSUE TITLE
Unified Platform

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#124]
Sidebar with 3 options as toggle for Registry, MRV and GHG Inventory. 

Toggle sidebar example as Focused/Other toggle.
<img width="244" alt="Screenshot 2023-07-13 at 11 53 43 AM" src="https://github.com/undp/carbon-registry/assets/109564/627b32a7-2561-4caa-b870-b78237aaafe4">

**Comment by sapumalxep** [comment]
Development complete for the backend and frontend. Will be moved to testing.

**Comment by sapumalxep** [comment]
Code synced with UNDP repo.
