### ISSUE TITLE
Authorization email not sent

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#126]

**Comment by sapumalxep** [comment]
@mbelinsky Since programme authorization happens in the registry, should this file be created in the registry or transparency system?

**Comment by sapumalxep** [comment]
Email will be sent. Authorization file changes will be done in a separate issue once clarififed.

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
#137
