### ISSUE TITLE
Specific Report File Types 

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#127]
should only be xls, xlsx, csv, or PDF

**Comment by sapumalxep** [comment]
Pull request created

**Comment by mbelinsky** [comment]
Not limited for example in `monitoring report`. Should only be xls, xlsx, ppt, pptx, csv, doc, docx, PDF, png, jpg

**Comment by sapumalxep** [comment]
Changes deployed.

**Comment by mbelinsky** [comment]
Will close when tied to commit

**Comment by sapumalxep** [comment]
Pull request created.
