### ISSUE TITLE
NDC action after approval

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#131]
Add a condition to add NDC action. Grey out "Add Action" button until methodology document is approved/programme is approved

**Comment by sapumalxep** [comment]
Pull request created

**Comment by mbelinsky** [comment]
Button is now missing, not greyed out/unclickable

**Comment by sapumalxep** [comment]
As we discussed previously, our design language is to hide buttons of all unauthorized actions. Please advise. If we are to make all buttons greyed out/unclickable for all buttons, will have additional development effort and require full testing cycle.

**Comment by sapumalxep** [comment]
Only do for this specific button.

**Comment by sapumalxep** [comment]
Issue moved to testing.

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
https://github.com/undp/carbon-registry/pull/188
