### ISSUE TITLE
Social and Environmental Risk Screening Checklist

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#141]
https://info.undp.org/sites/bpps/SES_Toolkit/Pages/Homepage.aspx -> Social and Environmental Screening Template in English, Spanish, French -> SESP Attachment 1

[UNDP Social and Environmental Screening Procedure Template_JULY2022_ENGLISH short.docx](https://github.com/undp/carbon-registry/files/12241973/UNDP.Social.and.Environmental.Screening.Procedure.Template_JULY2022_ENGLISH.short.docx)

**Comment by sapumalxep** [comment]
Where and how do we add this to the system?

**Comment by mbelinsky** [comment]
Under co-benefits: new table = `Social & Environmental Risk`
