### ISSUE TITLE
Getting ITMO API Key

### ISSUE THREAD

**Issue by Louvani** [undp/carbon-registry#146]
Hi,

I'm new to this project and I'm trying to configure the ITMO API key. I couldn't find any information about the ITMO platform in the README.

Can you please tell me where I can create an account on the ITMO dev platform?

Thanks,

**Comment by lance-jen** [comment]
Hi @Louvani 
you can register ITMO platform here [ITMO platform](https://carboncooperation.undp.org/)

**Comment by Louvani** [comment]
But this is develop enviroment?

I can see this allows to register developers or verifiers but it does not provides the API KEY

**Comment by humanitariantechie** [comment]
Hi @Louvani, 

The Carbon Registry is a separate application, thus the ITMO platform related env variables need to be recovered through the ITMO platform - the link as advised above

**Comment by humanitariantechie** [comment]
Closing this as not relevant for the carbon-registry development team
