### ISSUE TITLE
Upcoming Timeline

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#149]
Add next steps in activity timeline
https://www.figma.com/file/qTqBWdufgIxyEoz5Y2g59w?node-id=11376:16595&mode=design#539183725

**Comment by sapumalxep** [comment]
Design changes initiated.

**Comment by sapumalxep** [comment]
Need the list of exact events.
Dev Estimate - 2 days

**Comment by sapumalxep** [comment]
Refer figma for the events. Show until the credits are all issued. No need transfer, retire etc.

**Comment by sapumalxep** [comment]
Monitoring and Verification.

These two are NDC action related documents uploaded from the Transparency system. This does get communicated but not recorded in the activity timeline as we did not do any functionality changes on the Carbon Registry side when developing Transparency. Please advice @mbelinsky

**Comment by sapumalxep** [comment]
Pull request created for upcoming event apart from monitoring and verification. This will be done along with credit issuance tied with NDC actions.

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
![Screenshot 2023-11-13 at 3 57 53 PM](https://github.com/undp/carbon-registry/assets/109564/376caf99-1d77-4202-841b-5fbbf38ff641) 
Does not switch to next pending state after action (eg. monitoring)
