### ISSUE TITLE
Help Redirect

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#151]
In signup email, help hyperlink is already https://test.carbreg.org/help . Help URL should then redirect to FAQ URL. Currently dead link

**Comment by mbelinsky** [comment]
Text updated 855f627

**Comment by sapumalxep** [comment]
Dev estimate - 0.5 days

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
https://github.com/undp/carbon-registry/pull/198
