### ISSUE TITLE
Programme Document Descriptions

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#152]
Filename visible & should be hidden. Programme Document Descriptions, dates, times, version Missing. Eg "Design Document" "Methodology Document" "Monitoring Report 21 August 2023 @ 02:56 ~ V2".

**Comment by sapumalxep** [comment]
Duplicate of [Programme Documents Display#168](https://github.com/undp/carbon-registry/issues/168)?

**Comment by mbelinsky** [comment]
No

**Comment by sapumalxep** [comment]
Deployed.

**Comment by mbelinsky** [comment]
No documents are visible nor labels. Possible error: 
<img width="373" alt="Screenshot 2023-11-20 at 3 54 51 PM" src="https://github.com/undp/carbon-registry/assets/109564/b5282534-e0c7-4595-8eaf-129f34757435">

**Comment by mbelinsky** [comment]
16e6e19
