### ISSUE TITLE
Default Methodology

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#163]
- Should be `UNFCCC CDM`. 
- Should be a dropdown list, including `UNFCCC CDM`, `Gold Standard`, `Verra VCS`, `Other`

**Comment by sapumalxep** [comment]
Dev Estimate - 0.25 days

**Comment by mbelinsky** [comment]
Full list:
- "ACR - Truck Stop Electrification",
- "ACR - Advanced Refrigeration Systems",
- "ACR - Certified Reclaimed HFC Refrigerants, Propellants, and Fire Suppressants",
- "ACR - Destruction of Ozone Depleting Substances and High-GWP Foam",
- "ACR - Destruction of Ozone Depleting Substances from International Sources",
- "ACR - Transition to Advanced Formulation Blowing Agents in Foam Manufacturing and Use",
- "ACR - 	Afforestation and Reforestation of Degraded Lands",
- "ACR - Avoided Conversion of Grasslands and Shrublands to Crop Production",
- "ACR - Improved Forest Management (IFM) on Canadian Forestlands",
- "ACR - Improved Forest Management (IFM) on Non-Federal U.S. Forestlands",
- "ACR - Improved Forest Management (IFM) on Small Non-Industrial Private Forestlands",
- "ACR - Restoration of California Deltaic and Coastal Wetlands",
- "ACR - Restoration of Pocosin Wetlands",
- "ACR - Carbon Capture and Storage Projects",
- "ACR - Landfill Gas Destruction and Beneficial Use Projects",
- "CAR - Adipic Acid Production",
- "CAR - Biochar",
- "CAR - Canada Grassland",
- "CAR - Coal Mine Methane",
- "CAR - Forest",
- "CAR - Grassland",
- "CAR - Mexico Boiler Efficiency",
- "CAR - Mexico Forest",
- "CAR - Mexico Halocarbon",
- "CAR - Mexico Landfill",
- "CAR - Mexico Livestock",
- "CAR - Mexico Ozone Depleting Substances",
- "CAR - Nitric Acid Production",
- "CAR - Nitrogen Management",
- "CAR - Organic Waste Composting",
- "CAR - Organic Waste Digestion",
- "CAR - Ozone Depleting Substances",
- "CAR - Rice Cultivation",
- "CAR - Soil Enrichment",
- "CAR - Urban Forest Management",
- "CAR - Urban Tree Planting",
- "CAR - U.S. Landfill",
- "CAR - U.S. Livestock",
- "CDM - AM0001",
- "CDM - AM0007",
- "CDM - AM0009",
- "CDM - AM0017",
- "CDM - AM0018",
- "CDM - AM0019",
- "CDM - AM0020",
- "CDM - AM0021",
- "CDM - AM0023",
- "CDM - AM0026",
- "CDM - AM0027",
- "CDM - AM0028",
- "CDM - AM0030",
- "CDM - AM0031",
- "CDM - AM0035",
- "CDM - AM0036",
- "CDM - AM0037",
- "CDM - AM0038",
- "CDM - AM0043",
- "CDM - AM0044",
- "CDM - AM0045",
- "CDM - AM0046",
- "CDM - AM0048",
- "CDM - AM0049",
- "CDM - AM0050",
- "CDM - AM0052",
- "CDM - AM0053",
- "CDM - AM0055",
- "CDM - AM0056",
- "CDM - AM0057",
- "CDM - AM0058",
- "CDM - AM0059",
- "CDM - AM0060",
- "CDM - AM0061",
- "CDM - AM0062",
- "CDM - AM0063",
- "CDM - AM0064",
- "CDM - AM0065",
- "CDM - AM0066",
- "CDM - AM0067",
- "CDM - AM0068",
- "CDM - AM0069",
- "CDM - AM0070",
- "CDM - AM0071",
- "CDM - AM0072",
- "CDM - AM0073",
- "CDM - AM0074",
- "CDM - AM0075",
- "CDM - AM0076",
- "CDM - AM0077",
- "CDM - AM0078",
- "CDM - AM0079",
- "CDM - AM0080",
- "CDM - AM0081",
- "CDM - AM0082",
- "CDM - AM0083",
- "CDM - AM0084",
- "CDM - AM0086",
- "CDM - AM0088",
- "CDM - AM0089",
- "CDM - AM0090",
- "CDM - AM0091",
- "CDM - AM0092",
- "CDM - AM0093",
- "CDM - AM0094",
- "CDM - AM0095",
- "CDM - AM0096",
- "CDM - AM0097",
- "CDM - AM0098",
- "CDM - AM0099",
- "CDM - AM0100",
- "CDM - AM0101",
- "CDM - AM0103",
- "CDM - AM0104",
- "CDM - AM0105",
- "CDM - AM0106",
- "CDM - AM0107",
- "CDM - AM0108",
- "CDM - AM0109",
- "CDM - AM0110",
- "CDM - AM0111",
- "CDM - AM0112",
- "CDM - AM0113",
- "CDM - AM0114",
- "CDM - AM0115",
- "CDM - AM0116",
- "CDM - AM0117",
- "CDM - AM0118",
- "CDM - AM0119",
- "CDM - AM0120",
- "CDM - AM0121",
- "CDM - AM0122",
- "CDM - AMS-I.A.",
- "CDM - AMS-I.B.",
- "CDM - AMS-I.C.",
- "CDM - AMS-I.D.",
- "CDM - AMS-I.E.",
- "CDM - AMS-I.F.",
- "CDM - AMS-I.G.",
- "CDM - AMS-I.H.",
- "CDM - AMS-I.I.",
- "CDM - AMS-I.J.",
- "CDM - AMS-I.K.",
- "CDM - AMS-I.L.",
- "CDM - AMS-I.M.",
- "CDM - AMS-II.A.",
- "CDM - AMS-II.B.",
- "CDM - AMS-II.C.",
- "CDM - AMS-II.D.",
- "CDM - AMS-II.E.",
- "CDM - AMS-II.F.",
- "CDM - AMS-II.G.",
- "CDM - AMS-II.H.",
- "CDM - AMS-II.I.",
- "CDM - AMS-II.J.",
- "CDM - AMS-II.K.",
- "CDM - AMS-II.L.",
- "CDM - AMS-II.M.",
- "CDM - AMS-II.N.",
- "CDM - AMS-II.O.",
- "CDM - AMS-II.P.",
- "CDM - AMS-II.Q.",
- "CDM - AMS-II.R.",
- "CDM - AMS-II.S.",
- "CDM - AMS-II.T.",
- "CDM - AMS-III.A.",
- "CDM - AMS-III.B.",
- "CDM - AMS-III.C.",
- "CDM - AMS-III.D.",
- "CDM - AMS-III.E.",
- "CDM - AMS-III.F.",
- "CDM - AMS-III.G.",
- "CDM - AMS-III.H.",
- "CDM - AMS-III.I.",
- "CDM - AMS-III.J.",
- "CDM - AMS-III.K.",
- "CDM - AMS-III.L.",
- "CDM - AMS-III.M.",
- "CDM - AMS-III.N.",
- "CDM - AMS-III.O.",
- "CDM - AMS-III.P.",
- "CDM - AMS-III.Q.",
- "CDM - AMS-III.R.",
- "CDM - AMS-III.S.",
- "CDM - AMS-III.T.",
- "CDM - AMS-III.U.",
- "CDM - AMS-III.V.",
- "CDM - AMS-III.W.",
- "CDM - AMS-III.X.",
- "CDM - AMS-III.Y.",
- "CDM - AMS-III.Z.",
- "CDM - AMS-III.AA.",
- "CDM - AMS-III.AB.",
- "CDM - AMS-III.AC.",
- "CDM - AMS-III.AD.",
- "CDM - AMS-III.AE.",
- "CDM - AMS-III.AF.",
- "CDM - AMS-III.AG.",
- "CDM - AMS-III.AH.",
- "CDM - AMS-III.AI.",
- "CDM - AMS-III.AJ.",
- "CDM - AMS-III.AK.",
- "CDM - AMS-III.AL.",
- "CDM - AMS-III.AM.",
- "CDM - AMS-III.AN.",
- "CDM - AMS-III.AO.",
- "CDM - AMS-III.AP.",
- "CDM - AMS-III.AQ.",
- "CDM - AMS-III.AR.",
- "CDM - AMS-III.AS.",
- "CDM - AMS-III.AT.",
- "CDM - AMS-III.AU.",
- "CDM - AMS-III.AV.",
- "CDM - AMS-III.AW.",
- "CDM - AMS-III.AX.",
- "CDM - AMS-III.AY.",
- "CDM - AMS-III.BA.",
- "CDM - AMS-III.BB.",
- "CDM - AMS-III.BC.",
- "CDM - AMS-III.BD.",
- "CDM - AMS-III.BE.",
- "CDM - AMS-III.BF.",
- "CDM - AMS-III.BG.",
- "CDM - AMS-III.BH.",
- "CDM - AMS-III.BI.",
- "CDM - AMS-III.BJ.",
- "CDM - AMS-III.BK.",
- "CDM - AMS-III.BL.",
- "CDM - AMS-III.BM.",
- "CDM - AMS-III.BN.",
- "CDM - AMS-III.BO.",
- "CDM - AMS-III.BP.",
- "CDM - AR-AM0014",
- "CDM - AR-AMS0003",
- "CDM - AR-AMS0007",
- "GS - METHODOLOGY FOR METERED & MEASURED ENERGY COOKING DEVICES",
- "GS - METHODOLOGY FOR RETROFIT ENERGY EFFICIENCY MEASURES IN SHIPPING ",
- "GS - SOIL ORGANIC CARBON ACTIVITY MODULE FOR APPLICATION OF ORGANIC SOIL IMPROVERS FROM PULP AND PAPER MILL SLUDGES",
- "GS - REDUCED EMISSIONS FROM COOKING AND HEATING – TECHNOLOGIES AND PRACTICES TO DISPLACE DECENTRALIZED THERMAL ENERGY CONSUMPTION (TPDDTEC)",
- "GS - CARBON SEQUESTRATION THROUGH ACCELERATED CARBONATION OF CONCRETE AGGREGATE ",
- "VCS - VM0001",
- "VCS - VM0002",
- "VCS - VM0003",
- "VCS - VM0004",
- "VCS - VM0005",
- "VCS - VM0006",
- "VCS - VM0007",
- "VCS - VM0008",
- "VCS - VM0009",
- "VCS - VM0010",
- "VCS - VM0011",
- "VCS - VM0012",
- "VCS - VM0013",
- "VCS - VM0014",
- "VCS - VM0015",
- "VCS - VM0016",
- "VCS - VM0017",
- "VCS - VM0018",
- "VCS - VM0019",
- "VCS - VM0020",
- "VCS - VM0021",
- "VCS - VM0022",
- "VCS - VM0023",
- "VCS - VM0024",
- "VCS - VM0025",
- "VCS - VM0026",
- "VCS - VM0027",
- "VCS - VM0028",
- "VCS - VM0029",
- "VCS - VM0030",
- "VCS - VM0031",
- "VCS - VM0032",
- "VCS - VM0033",
- "VCS - VM0034",
- "VCS - VM0035",
- "VCS - VM0036",
- "VCS - VM0037",
- "VCS - VM0038",
- "VCS - VM0039",
- "VCS - VM0040",
- "VCS - VM0041",
- "VCS - VM0042",
- "VCS - VM0043",
- "VCS - VMR000",
- "VCS - VMR006"
- ID_PM044
- ID_PM043
- ID_PM042
- ID_PM041
- ID_PM040
- ID_PM039
- ID_AM028
- ID_AM027
- ID_AM026
- ID_AM025
- ID_AM024
- ID_AM023
- ID_AM022
- ID_AM021
- ID_AM020
- ID_AM006
- VN_PM028
- ID_AM019
- VN_PM027
- ID_AM018
- ID_AM007
- TH_PM026
- VN_PM026
- VN_PM025
- TH_PM025
- ID_AM009
- VN_PM024
- ID_AM017
- TH_PM024
- ID_AM016
- VN_PM023
- TH_PM023
- ID_AM015
- TH_PM022
- VN_AM015
- VN_AM009
- ID_AM014
- TH_PM021
- TH_AM017
- ID_AM013
- VN_AM014
- VN_AM013
- TH_AM016
- VN_AM012
- TH_AM015
- ID_AM011
- TH_AM001
- VN_AM011
- ID_AM012
- VN_AM010
- TH_AM014
- ID_AM008
- VN_AM006
- TH_AM013
- TH_AM012
- VN_AM004
- ID_AM005
- ID_AM004
- TH_AM011
- VN_AM003
- ID_AM003
- VN_AM002
- TH_AM010
- ID_AM002
- TH_AM009
- ID_AM010
- VN_AM008
- TH_AM008
- TH_AM005
- VN_AM007
- TH_AM007
- VN_AM001
- MM_PM007
- TH_AM006
- MM_PM006
- VN_AM005
- KH_AM004
- TH_AM002
- KH_AM005
- BD_PM005
- MM_AM005
- TH_AM004
- LA_AM004
- BD_AM001
- MN_AM003
- MM_AM004
- KE_AM003
- LA_AM003
- MM_AM003
- CR_AM003
- KH_AM003
- PH_PM003
- TH_AM003
- CL_AM001
- ET_AM003
- BD_AM003
- BD_AM002
- ET_AM002
- KE_AM002
- CR_AM002
- LA_AM002
- KH_AM002
- MV_AM002
- MM_AM002
- PH_AM002
- MN_AM002
- CL_AM002
- PW_AM001
- PH_AM001
- KE_AM001
- KH_AM001
- SA_AM001
- MN_AM001
- MM_AM001
- CR_AM001
- ID_AM001
- MX_AM001
- ET_AM001
- LA_AM001
- MV_AM001
- "Puro - BIO CHAR"

**Comment by sapumalxep** [comment]
Do we need list all methodologies in the above comment or just the high level methodology type? Currently we only show "Gold Standard" and doesn't refer to exact methodology. @mbelinsky

**Comment by sapumalxep** [comment]
Recommended to add another field on exact methodology.
