### ISSUE TITLE
Link to Design a Project Document

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#167]
Under `https://transparency-demo.carbreg.org/programmeManagement/addProgramme` Add an info rollover to `Design Document` reading `Design a Project Document with the UNFCCC CDM Mechanism Tool Prototype` with a hyperlink to https://app-eff78ffabc4efb.app.unfccc.org/tools/cdm/testprodspt3/UNFCCC_CDM/Pages/PDDnew.aspx?t=pdd

**Comment by sapumalxep** [comment]
Dev Estimate 0.5 days.
Need further clarification on where the roll-over should appear.

**Comment by sapumalxep** [comment]
Information shown on (i) in MRV.

**Comment by sapumalxep** [comment]
Issue moved to testing.

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
Error: Info tip reads `designDocTooltip` not `Design a Project Document with the UNFCCC CDM Mechanism Tool Prototype`
