### ISSUE TITLE
Methodology Estimated Credits Not Required

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#170]
In `https://transparency-demo.carbreg.org/programmeManagement/addNdcAction`, `Methodology Estimated Credits` should not be required. Currently facing error `Methodology Estimated Credits should be greater than O`

**Comment by sapumalxep** [comment]
If a methodology is not implemented, will allow to go ahead with methodology estimated credits = 0.

Dev Estimate - 0.5 days

**Comment by mbelinsky** [comment]
16e6e19
