### ISSUE TITLE
Account creation on test server

### ISSUE THREAD

**Issue by timschloe** [undp/carbon-registry#185]
See screenshots.
![Screenshot from 2023-10-17 14-39-42](https://github.com/undp/carbon-registry/assets/6918041/d56b46ae-df5f-4772-9cf9-7e5f1a312360)
![Screenshot from 2023-10-17 14-39-37](https://github.com/undp/carbon-registry/assets/6918041/4717d320-bc56-490c-a1da-7156d8348503)

I tried all the obvious things like changing browser and couldn't get around it.

**Comment by sapumalxep** [comment]
The issue is fixed.
