### ISSUE TITLE
Government Department Field

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#234]
`Government Department` is sub-ministerial

Default enum values=
- Agriculture
- Agriculture - Cocoa Research Institute
- Agriculture - National Agricultural Extension, Research and Liaison Services
- Agriculture - National Veterinary Research Institute
- Agriculture - Agricultural Insurance Corporation
- Agriculture - National Root Crops Research Institute
- Agriculture - Agricultural Research Council
- Agriculture - Institute for Oceanography and Marine Research
- Agriculture - Institute for Oil Palm Research
- Agriculture - Agricultural Quarantine Service
- Agriculture - National Horticultural Research Institute

- Aviation
- Aviation - Federal Airports Authority
- Aviation - Airspace Management Agency
- Aviation - Civil Aviation Authority
- Aviation - Safety Investigation Bureau
- Aviation - Meteorological Agency
- Aviation - College of Aviation Technology

- Communications
- Communications - National Information Technology Development Agency
- Communications - Communications Satellite Limited
- Communications - Broadcasting Commission
- Communications - Communications Commission
- Communications - Postal Service
- Communications - National Frequency Management Council
- Communications - Television Authority
- Communications - Galaxy Backbone

- Economy
- Economy - Asset Management Corporation
- Economy - Social Security Administration
- Economy - Budget Office of the Federation
- Economy - Bureau of Public Enterprises
- Economy - Bureau of Public Procurement
- Economy - Central Bank
- Economy - Corporate Affairs Commission
- Economy - Debt Management Office
- Economy - Inland Revenue Service
- Economy - Mortgage Bank
- Economy - Fiscal Responsibility Commission
- Economy - Infrastructure Concession Regulatory Commission
- Economy - National Bureau of Statistics
- Economy - National Council on Privatisation
- Economy - National Insurance Commission
- Economy - National Pension Commission
- Economy - National Planning Commission
- Economy - National Sugar Development Council
- Economy - Niger Delta Development Commission
- Economy - Customs Service
- Economy - Deposit Insurance Corporation
- Economy - Investment Promotion Commission
- Economy - Export - Import Bank
- Economy - Export Promotion Council
- Economy - Oil and Gas Free Zones Authority
- Economy - Export Processing Zones Authority
- Economy - Revenue Mobilisation Allocation and Fiscal Commission
- Economy - Securities and Exchange Commission
- Economy - Standards Organisation
- Economy - Small and Medium Enterprise Development Agency 

- Education
- Education - National Board for Arabic And Islamic Studies
- Education - Joint Admissions and Matriculation Board
- Education - National Examination Council
- Education - National Open University
- Education - National Teachers Institute
- Education - National Universities Commission
- Education - Tertiary Education Trust Fund
- Education - Teachers Registration Council
- Education - National Business and Technical Examinations Board
- Education - Universal Basic Education Commission
- Education - West African Examination Council
- Education - National Commission for Colleges of Education
- Education - National Library

- Energy
- Energy - Midstream and Downstream Petroleum Regulatory Authority
- Energy - Upstream Petroleum Regulatory Commission
- Energy - Electricity Management Services Limited
- Energy - Energy Commission
- Energy - National Power Training Institute
- Energy - Electricity Regulatory Commission
- Energy - Content Monitoring and Development Board
- Energy - National Petroleum Corporation
- Energy - Nuclear Regulatory Authority
- Energy - Petroleum Product Pricing Regulatory Agency
- Energy - Power Holding Company (defunct)
- Energy - Rural Electrification Agency
- Energy - Transmission Company

- Environment
- Environment - Environmental Protection Agency (defunct)
- Environment - Forestry Research Institute
- Environment - National Biosafety Management Agency
- Environment - National Environmental Standards and Regulations Enforcement Agency
- Environment - National Oil Spill Detection and Response Agency
- Environment - Environmental Health Officers Registration Council

- Health
- Health - National Health Insurance Scheme
- Health - Institute for Pharmaceutical Research and Development
- Health - Agency for the Control of AIDS
- Health - Agency for Food and Drug Administration and Control
- Health - Primary Health Care Development Agency
- Health - Institute of Medical Research
- Health - Centre for Disease Control
- Health - Drug Law Enforcement Agency

- Intelligence
- Intelligence - Defence Intelligence Agency
- Intelligence - State Security Service
- Intelligence - National Intelligence Agency
- Intelligence - Financial Intelligence Unit

- Judiciary
- Judiciary - National Judicial Council
- Judiciary - Federal Judicial Service Commission
- Judiciary - National Judicial Institute

- Maritime
- Maritime - Maritime Administration and Safety Agency
- Maritime - Ports Authority
- Maritime - Shippers' Council

- Media
- Media - Broadcasting Organisation
- Media - News Agency
- Media - Press Council
- Media - Television Authority

- Science and Technology
- Science and Technology - Agency For Science and Engineering Infrastructure
- Science and Technology - Biotechnology Development Agency
- Science and Technology - Centre for Remote Sensing
- Science and Technology - Science and Technology Complex
- Science and Technology - Office for Technology Acquisition and Promotion
- Science and Technology - Space Research and Development Agency
- Science and Technology - Nuclear Regulatory Authority
- Science and Technology - Raw Materials Research and Development Council
- Science and Technology - Communications Satellite Ltd
- Science and Technology - Centre for Technology Management

- Water Resources
- Water Resources - Hydrological Services Agency
- Water Resources - Integrated Water Resources Commission
- Water Resources - Water Resources Institute
- Water Resources - River Basin Development Authorities

- Uncategorised
- Uncategorised - Centre for Black and African Arts and Civilization
- Uncategorised - Automotive Design and Development Council
- Uncategorised - Code of Conduct Bureau
- Uncategorised - Computer Professionals Registration Council
- Uncategorised - Consumer Protection Council
- Uncategorised - Economic and Financial Crimes Commission
- Uncategorised - Federal Character Commission
- Uncategorised - Federal Housing Authority
- Uncategorised - Corrupt Practices and Other Related Offences Commission
- Uncategorised - Independent National Electoral Commission
- Uncategorised - Industrial Training Fund
- Uncategorised - Legal Aid Council
- Uncategorised - Agency for the Prohibition of Trafficking in Persons
- Uncategorised - National Boundary Commission
- Uncategorised - National Council of Arts and Culture
- Uncategorised - Economic Reconstruction Fund
- Uncategorised - Emergency Management Agency
- Uncategorised - Hajj Commission
- Uncategorised - Human Rights Commission
- Uncategorised - Identity Management Commission
- Uncategorised - Institute for Hospitality Tourism
- Uncategorised - Lottery Regulatory Commission
- Uncategorised - Orientation Agency
- Uncategorised - Population Commission
- Uncategorised - Poverty Eradication Programme (defunct)
- Uncategorised - Salaries, Incomes and Wages Commission
- Uncategorised - Sports Commission
- Uncategorised - Extractive Industries Transparency Initiative
- Uncategorised - Immigration Service
- Uncategorised - Building and Road Research Institute
- Uncategorised - Institute of Building
- Uncategorised - Christian Pilgrim Commission
- Uncategorised - Copyright Commission
- Uncategorised - Tourism Development Corporation
- Uncategorised - Public Complaints Commission
- Uncategorised - Surveyors Council
- Uncategorised - National Lottery Trust Fund

**Comment by sapumalxep** [comment]
Uncategorized as "Other" ministry
