### ISSUE TITLE
Configuration for docker-compose

### ISSUE THREAD

**Issue by martinvalenta** [undp/carbon-registry#56]
What changes in `docker-compose.yml` are required so that I can log in locally? Only setting `rootEmail` doesn't work.

**Comment by timschloe** [comment]
same question here, I still fail to set up the accounts.

**Comment by palindaa** [comment]
Please check the updated documentation in the develop branch. https://github.com/undp/carbon-registry/tree/develop#run-services-as-containers. Please use develop branch

**Comment by timschloe** [comment]
> Please check the updated documentation in the develop branch. https://github.com/undp/carbon-registry/tree/develop#run-services-as-containers. Use develop branch as well.

I'm gettting
Error: No such container: undp-carbon-registry-national-1
=> docker ps gives

CONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS         PORTS                            NAMES
3fbc9fb7391a   carbon-registry_stats   "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes   0.0.0.0:3100->3100/tcp           carbon-registry_stats_1
7ecbe663e4f8   carbon-registry_web     "/docker-entrypoint.…"   3 minutes ago   Up 3 minutes   80/tcp, 0.0.0.0:3030->3030/tcp   carbon-registry_web_1
9139428d81ad   postgres                "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes   0.0.0.0:5432->5432/tcp           db

Neither of the two container logs has the word "temporary" in it.

Retrying with email, but pain to get SMTP up...

**Comment by palindaa** [comment]
Please verify your national docker container has environment variable ` IS_EMAIL_DISABLED` and value set to "true". 

If not please update the git with latest main branch changes.

**Comment by timschloe** [comment]
thank you, resolved this one. There will be a few more coming, I'm a noob & Mark is sick, sorry.
(my goal is to have a copy-pasteable install guide from SSh into a fresh, plain alpine Linode)

**Comment by palindaa** [comment]
Happy to help. and please let me know if any missing parts in the documentation. I'll improve the documentation as well.

**Comment by timschloe** [comment]
Building a new container right now.

As soon as I'm in my own system as admin, I'll do an installation run through on Twitch :-) I'm thinking of a tutorial series for the key elements of setting up nationally. (next videos then need to include changing country name etc. pp.)
