### ISSUE TITLE
User Creation / Password Reset

### ISSUE THREAD

**Issue by timschloe** [undp/carbon-registry#61]
Now inside a local install of the registry. Am I correct in the assumption that I cannot create user passwords manually in the GUI, but only auto-generate by email resp. would need to go into the PostGres directly if I wanted to edit passwords manually? 

We want to do an interactive Demo of the registry next week, and I need to be able to play around with the system with multiple users to figure out what kinds of tasks we can give them. 

@palindaa Would it be possible to give me an admin account on a robust, online install where I can prepare an experience for multiple users that can actually send emails and set passwords? Would also be critical to add some programmes.

Sorry, was planning to do this with @mbelinsky but afraid currently you are the only hope to get there in time...

P.S. 
This seems unusually complex compared to other open source admin panels - e.g. Mastodon, Peertube, Nextcloud and Funkwhale all allow admin to manually reset passwords in the GUI?

**Comment by palindaa** [comment]
@timschloe yes. Cannot create user passwords manually

Can give admin, programme developer and certifier account passwords with programmes. How can I send you the credentials. Shall I email? (Please send me your email)

Will check on that and let you know.

**Comment by palindaa** [comment]
@timschloe  we can make a change to give user password at the user add from the GUI. But I assume we need to check with @mbelinsky on that, since we are doing a small user process change.

**Comment by timschloe** [comment]
> @timschloe yes. Cannot create user passwords manually
> 
> Can give admin, programme developer and certifier account passwords with programmes. How can I send you the credentials. Shall I email? (Please send me your email)
> 
> Will check on that to make it bit easy and let you know.

That would be tim.reutemann@undp.org
