### ISSUE TITLE
Updated D4C Support Images

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#76]
Adjust UNDP logo to only image. Add logos for other D4C partners:
D4C is a collaboration between the European Bank for Reconstruction and Development (EBRD), United Nations Development Program (UNDP), United Nations Framework Convention on Climate Change (UNFCCC), International Emissions Trading Association (IETA), European Space Agency (ESA), and World Bank Group

**Comment by sapumalxep** [comment]
Design Review sent for clarifications.

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
#139
