### ISSUE TITLE
Real Time List of Certifiers

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#77]
Pull list from https://cdm.unfccc.int/

**Comment by mbelinsky** [comment]
Scraped annually

**Comment by sapumalxep** [comment]
Which to used as the Tax ID of certifier? (mandatory field of our systems)

**Comment by sapumalxep** [comment]
Tax ID as company name

**Comment by sapumalxep** [comment]
Issue moved to testing.

**Comment by sapumalxep** [comment]
Will be tested along with Unified System.

**Comment by dubgeis** [comment]
@mbelinsky would like to discuss how we can leverage this with https://github.com/hashgraph/guardian for active data from VVBs/DOE for project data. We have an initiative to enable all Certifiers similar roles with credential issuance capabilities. cc: @Neurone

**Comment by sapumalxep** [comment]
Pull request created.
