### ISSUE TITLE
Add Analytics

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#88]
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3270907,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by palindaa** [comment]
Added the code snippet to https://www.test.carbreg.org/ system.

**Comment by mbelinsky** [comment]
#97
