### ISSUE TITLE
Integration with Climate Action Data Trust

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#93]
https://github.com/Chia-Network/cadt

**Comment by mbelinsky** [comment]
API Documentation https://github.com/Chia-Network/cadt/blob/main/docs/cadt_rpc_api.md

**Comment by sapumalxep** [comment]
Awaiting field mapping.

**Comment by sapumalxep** [comment]
Will provide timeline based on field mapping.

**Comment by sapumalxep** [comment]
Pull request created.

**Comment by mbelinsky** [comment]
Needs documentation in https://github.com/undp/carbon-registry/tree/main/modules to close.

**Comment by palindaa** [comment]
Added documentation https://github.com/undp/carbon-registry/pull/217

**Comment by mbelinsky** [comment]
591b5da
