### ISSUE TITLE
New Chat Support Function

### ISSUE THREAD

**Issue by mbelinsky** [undp/carbon-registry#95]
Typeform being deprecated August 31 https://community.typeform.com/typeform-updates-24/chat-ui-discontinuation-update-9435

**Comment by mbelinsky** [comment]
- Replace with https://www.tawk.to/ 
- Add Knowledge Base as {{helpDoc}}

**Comment by sapumalxep** [comment]
@mbelinsky Please create an account and send the tag.

**Comment by mbelinsky** [comment]
Created. Credentials sent via email.

**Comment by sapumalxep** [comment]
Added given codes to demo.carbreg.org and test.carbreg.org.
